name: "Alessio"
version: "0.0.1"
slug: "alessio"
description: "Share Home Assistant entities with Alexa"
url: "https://github.com/Sgobbit/hassio-addons/tree/main/alessio"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
startup: before
ports:
  80/tcp: 80
options:
  verbose: false
schema:
  verbose: bool
